name: ZkProgram Credential Proving

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.1.0
    - name: Install dependencies
      run: |
        cd starter-contracts/5-zk-program-credential-proof/
        npm install
        cd ../../../
    - name: Build and Run
      working-directory: ./starter-contracts/5-zk-program-credential-proof/
      run: npm run build && node build/src/RunInteraction.js
