name: ZkProgram Credential Proving

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.1.0

    - name: Install dependencies
      run: |
        cd starter-contracts/5-zk-program-credential-proof/
        git init
        npm install
        npm install snarkyjs mina-signer
        npm install --save-dev @types/node

    - name: Build and Run
      run: |
        cd starter-contracts/5-zk-program-credential-proof/
        npm run build && node build/src/RunInteraction.js
